title: Eric C. Singers Blog
description: Just another blog
author: Eric C. Singer

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

theme: jekyll-theme-hacker

# Conversion
markdown: kramdown
highlighter: rouge