title: Eric C. Singers Blog
description: Just another blog
author: 
  fullname:  Eric C. Singer
  twitter: esinger
  github: ericcsinger
  stackoverflow: 1239030
  rss: true



plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

theme: jekyll-theme-hacker

# Conversion
markdown: kramdown
highlighter: rouge